CREATE TABLE IF NOT EXISTS `mod_daily_challenge` (
  `guid` INT UNSIGNED NOT NULL,
  `last_reset` INT UNSIGNED NOT NULL DEFAULT 0,
  `challenge_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `progress` INT UNSIGNED NOT NULL DEFAULT 0,
  `completed` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `rewarded` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
